### ISSUE TITLE
PhpUnit process isolation

### ISSUE THREAD

**Issue by matiux** [dmaicher/doctrine-test-bundle#67] opened 2018-11-05 16:21 UTC
I'm working on sf 4.1.7 with phpunit 7.4.
If I run tests with `process isolation = true`, tests are not transactional :confused:
Instead with `process isolation = false` all works well

**Comment by dmaicher** [comment] 2018-11-13 15:21
This is a duplicate of https://github.com/dmaicher/doctrine-test-bundle/issues/66, right? I'm on vacation currently but feel free to give it a try yourself and contribute the fix :)

**Comment by dmaicher** [comment] 2018-11-22 09:48
Duplicate of https://github.com/dmaicher/doctrine-test-bundle/issues/66

**Closed by dmaicher** 2018-11-22 09:48 UTC
