### ISSUE TITLE
Failing Behat test does not lead to rollback?

### ISSUE THREAD

**Issue by NicoHaase** [dmaicher/doctrine-test-bundle#137] opened 2020-12-03 15:43 UTC
In one of our behat testsuites, we test for JSON responses using `behatch/contexts` (currently using v3.3.0). In their [JsonContext](https://github.com/Behatch/contexts/blob/master/src/Context/JsonContext.php), they throw a generic `Exception` on a failing test. This does not trigger `\DAMA\DoctrineTestBundle\Behat\BehatListener::rollBack`, leaving the database in a manipulated state. Is this expected behaviour? Is there something you can do to avoid this?

**Comment by dmaicher** [comment] 2020-12-03 16:28
ping @wouterj any idea?

**Comment by wouterj** [comment] 2020-12-16 22:24
Hi!

I cannot reproduce this locally unfortunately. See 26d6b11 for what I tried (throwing a generic `Exception` and then checking if `rollBack` is called using the good old `var_dump`).

**Comment by NicoHaase** [comment] 2020-12-17 08:09
Pretty strange. Two weeks ago, I could reproduce that nearly(!) each call. Now I'm no longer able to reproduce it, and I cannot see any configuration changes on our side that could have helped to resolve the issue :(

**Comment by dmaicher** [comment] 2020-12-17 08:24
Thanks a lot for checking @wouterj :+1: 

@NicoHaase closing here for now. Please re-open if there is something reproducible that we can look into.

**Closed by dmaicher** 2020-12-17 08:24 UTC
