### ISSUE TITLE
Combining Sentry with this bundle breaks test when data is inserted

### ISSUE THREAD

**Issue by bobvandevijver** [dmaicher/doctrine-test-bundle#196] opened 2022-01-26 09:47 UTC
Follow-up from #194. 

It appears that using Sentry in combination with this bundle, the tests break when new data is inserted into the database, with the cryptic (probably PDO) error "There is no active transaction". Disabling Sentry in the test environment solves the issue for us.

It seemed the following caused the transaction to trigger:

```php
class SomeTest extends KernelTestCase
{
  private Registry $doctrine;

  protected function setUp(): void
  {
    self::bootKernel();
    $this->doctrine = self::getContainer()->get('doctrine');
  }

  public function testSomething()
  {
    $entity = new Entity();

    $this->doctrine->getManager()->persist($entity);
    $this->doctrine->getManager()->flush();

    $this->assertTrue(true); // To avoid risky test warning
  }
}
```

**Comment by dmaicher** [comment] 2022-01-26 12:37
Unfortunately I cannot reproduce it. I tried installing https://github.com/getsentry/sentry-symfony on one of my apps. Tests are passing fine.

In case you can provide a minimal reproducer please let me know. Until then I will close here for now.

**Comment by Marmelatze** [comment] 2022-01-26 14:37
Same error for me with 6.7.3 in `PostConnectEventListener` the `$connection->getDriver()` is an instance of `\Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV2`. I'm not sure if this is the problem?

**Comment by dmaicher** [comment] 2022-01-26 14:45
Happy to look into it in case you can provide a small reproducer. Might indeed be related to the driver :thinking: 

Can maybe be fixed with priorities somehow for decorating the doctrine dbal driver

**Comment by Marmelatze** [comment] 2022-01-26 14:46
disabling sentry tracing for the test environment fixed it for me:

```
# config/test/sentry.yaml
sentry:
  tracing:
    enabled: false
```

**Comment by dmaicher** [comment] 2022-01-26 15:09
Actually this seems hard to fix :confused: 

The driver instance is replaced in a rather "hacky" way here:

https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/ConnectionConfigurator.php#L43

With DBAL v3 this will be fine as Sentry is using middlewares then

**Comment by Marmelatze** [comment] 2022-01-26 15:11
yes, just noticed when setting up a small project to reproduce, that it works with DBAL 3 :)
Disabling sentry in test env is a suitable workaround (at least for me, as there is no error logging needed usually)

**Comment by dmaicher** [comment] 2022-01-26 15:25
I still think that I need to fix this somehow as potentially decorating the driver might still happen in some other cases.

See https://github.com/dmaicher/doctrine-test-bundle/pull/197

Does this fix the issue for you with enabled Sentry tracing @Marmelatze ?

**Comment by Marmelatze** [comment] 2022-01-26 15:36
Yes that works for me with enabled tracing.

**Closed** 2022-01-26 19:38 UTC
Labels: bug

**Comment by bobvandevijver** [comment] 2022-01-27 10:50
@dmaicher Thank you for your effort looking into this! Really appreciated 👏🏻

I still disabled Sentry tracing for our test environment (thank you for the suggestion @Marmelatze, I previously just disabled the whole bundle for test, but this has less impact).

**Comment by Tofandel** [comment] 2022-03-17 18:49
Hmm I'm getting this issue as well, but 
```yaml
# config/test/sentry.yaml
sentry:
  tracing:
    enabled: false
```

doesn't fix it

I'm also getting several warnings
```
  2x: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV3" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release
.
    2x in AppTest::testDefaultRedirect from App\Tests

  1x: The "DAMA\DoctrineTestBundle\Doctrine\DBAL\AbstractStaticDriver" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.
    1x in PHPUnitExtension::executeBeforeFirstTest from DAMA\DoctrineTestBundle\PHPUnit
```

Has there been any developement on this that hasn't made it to this thread?

```php
namespace App\Tests;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class AppTest extends WebTestCase
{
    public function testDefaultRedirect(): void
    {

        $userRepository = static::getContainer()->get(UserRepository::class);
        $userRepository->findOneByEmail('role_admin@test.com');
        $this->assertTrue(true);
      }
}
```

This is the kind of test that will trigger this error in my case (just fetching data)

**Comment by dmaicher** [comment] 2022-03-18 10:55
@Tofandel what is the issue exactly for you? You can some `There is no active transaction` exception?

**Comment by Tofandel** [comment] 2022-03-18 11:19
Yes this is the exact same error and if I disable sentry completely it's gone, but just disabling tracing doesn't solve it anymore

**Comment by dmaicher** [comment] 2022-03-18 11:43
And you are using `v6.7.5` of this bundle? :thinking:

**Comment by Tofandel** [comment] 2022-03-18 11:44
Yes

```
            "name": "dama/doctrine-test-bundle",
            "version": "v6.7.5",
            "source": {
                "type": "git",
                "url": "https://github.com/dmaicher/doctrine-test-bundle.git",
                "reference": "af6f8e8c56fcfdf2ae039b97607883961a14af9c"
            },
```

**Comment by dmaicher** [comment] 2022-03-18 11:46
Can you provide a minimal reproducer?
