### ISSUE TITLE
Server has gone away on rollback

### ISSUE THREAD

**Issue by Soullivaneuh** [dmaicher/doctrine-test-bundle#46] opened 2017-10-24 13:21 UTC
Some time, but not all time, I get this error:

```
sullivan@58d5a9588f74:/code$ make coverage
php -dzend_extension=xdebug.so `which phpunit` --coverage-text --colors=never --coverage-html coverage

 // Clearing the cache for the test environment with debug true                                                         

 [OK] Cache for the "test" environment (debug=true) was successfully cleared.                                           

PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

.....................
Remaining vendor deprecation notices (76)
PDO::rollBack(): MySQL server has gone away

Remaining vendor deprecation notices (76)
```

So I can't tell you where is the issue, but I have this since this test adding:

```php
namespace Tests\AppBundle\Controller;

use AppBundle\Entity\Repository;
use AppBundle\Event\GithubHookEvent;
use AppBundle\Event\GitlabHookEvent;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * @author Sullivan Senechal <soullivaneuh@gmail.com>
 */
final class HookControllerTest extends WebTestCase
{
    private const TEST_ACCESS_TOKEN = 'access-token';
    private const TEST_SECRET_TOKEN = 'secret-token';

    public function testUnknownPlatform(): void
    {
        $client = static::createClient();
        $client->request('POST', '/hooks/foo');

        static::assertSame(404, $client->getResponse()->getStatusCode());
    }

    public function testUnknownRepository(): void
    {
        $client = static::createClient();
        $client->request(
            'POST',
            '/hooks/github',
            [],
            [],
            [
                'HTTP_X_GITHUB_EVENT' => 'ping',
            ],
            \json_encode([
                'repository' => [
                    'id' => 133742,
                ],
            ])
        );

        static::assertSame(404, $client->getResponse()->getStatusCode());
    }

    public function testNotEnabledRepository(): void
    {
        $client = static::createClient();
        $objectManager = $client->getContainer()->get('doctrine')->getManager();
        $repository = (new Repository())
            ->setName('foo/bar')
            ->setEnabled(false)
            ->setSecretToken(self::TEST_SECRET_TOKEN)
            ->setPlatform('github')
            ->setPlatformId(42);
        $objectManager->persist($repository);
        $objectManager->flush();

        $client->request(
            'POST',
            '/hooks/github',
            [],
            [],
            [
                'HTTP_X_GITHUB_EVENT' => 'ping',
            ],
            \json_encode([
                'repository' => [
                    'id' => 42,
                ],
            ])
        );

        static::assertSame(
            404,
            $client->getResponse()->getStatusCode(),
            'Not enabled repositories should not be handled.'
        );
    }

    public function testBadPayloadSignature(): void
    {
        $client = static::createClient();
        $objectManager = $client->getContainer()->get('doctrine')->getManager();
        $repository = (new Repository())
            ->setName('foo/bar')
            ->setEnabled(true)
            ->setSecretToken(self::TEST_SECRET_TOKEN)
            ->setPlatform('github')
            ->setPlatformId(42);
        $objectManager->persist($repository);
        $objectManager->flush();

        $client->request(
            'POST',
            '/hooks/github',
            [],
            [],
            [
                'HTTP_X_GITHUB_EVENT' => 'ping',
                'HTTP_X_HUB_SIGNATURE' => 'fake-sign',
            ],
            \json_encode([
                'repository' => [
                    'id' => 42,
                ],
            ])
        );

        static::assertSame(400, $client->getResponse()->getStatusCode());
    }

    public function testGithubPing(): void
    {
        $client = static::createClient();
        $objectManager = $client->getContainer()->get('doctrine')->getManager();
        $repository = (new Repository())
            ->setName('foo/bar')
            ->setEnabled(true)
            ->setSecretToken(self::TEST_SECRET_TOKEN)
            ->setPlatform('github')
            ->setPlatformId(42);
        $objectManager->persist($repository);
        $objectManager->flush();

        $body = \json_encode([
            'repository' => [
                'id' => 42,
            ],
        ]);
        $signature = \hash_hmac('sha1', $body, self::TEST_SECRET_TOKEN);

        $client->request(
            'POST',
            '/hooks/github',
            [],
            [],
            [
                'HTTP_X_GITHUB_EVENT' => 'ping',
                'HTTP_X_HUB_SIGNATURE' => "sha1={$signature}",
            ],
            $body
        );

        static::assertSame(200, $client->getResponse()->getStatusCode());
        static::assertSame('pong!', $client->getResponse()->getContent());
    }

    public function testGithubPush(): void
    {
        $client = static::createClient();
        $objectManager = $client->getContainer()->get('doctrine')->getManager();
        $repository = (new Repository())
            ->setName('baxterthehacker/public-repo')
            ->setEnabled(true)
            ->setAccessToken(self::TEST_ACCESS_TOKEN)
            ->setSecretToken(self::TEST_SECRET_TOKEN)
            ->setPlatform('github')
            ->setPlatformId(4242);
        $objectManager->persist($repository);
        $objectManager->flush();

        $body = \json_encode([
            'ref' => 'refs/heads/changes',
            'before' => '9049f1265b7d61be4a8904a9a27120d2064dab3b',
            'after' => '0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
            'created' => false,
            'deleted' => false,
            'forced' => false,
            'base_ref' => null,
            'compare' => 'https://github.com/baxterthehacker/public-repo/compare/9049f1265b7d...0d1a26e67d8f',
            'commits' => [
                [
                    'id' => '0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
                    'tree_id' => 'f9d2a07e9488b91af2641b26b9407fe22a451433',
                    'distinct' => true,
                    'message' => 'Update README.md',
                    'timestamp' => '2015-05-05T19:40:15-04:00',
                    'url' => 'https://github.com/baxterthehacker/public-repo/commit/0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
                    'author' => [
                        'name' => 'baxterthehacker',
                        'email' => 'baxterthehacker@users.noreply.github.com',
                        'username' => 'baxterthehacker',
                    ],
                    'committer' => [
                        'name' => 'baxterthehacker',
                        'email' => 'baxterthehacker@users.noreply.github.com',
                        'username' => 'baxterthehacker',
                    ],
                    'added' => [
                    ],
                    'removed' => [
                    ],
                    'modified' => [
                        'README.md',
                    ],
                ],
            ],
            'head_commit' => [
                'id' => '0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
                'tree_id' => 'f9d2a07e9488b91af2641b26b9407fe22a451433',
                'distinct' => true,
                'message' => 'Update README.md',
                'timestamp' => '2015-05-05T19:40:15-04:00',
                'url' => 'https://github.com/baxterthehacker/public-repo/commit/0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
                'author' => [
                    'name' => 'baxterthehacker',
                    'email' => 'baxterthehacker@users.noreply.github.com',
                    'username' => 'baxterthehacker',
                ],
                'committer' => [
                    'name' => 'baxterthehacker',
                    'email' => 'baxterthehacker@users.noreply.github.com',
                    'username' => 'baxterthehacker',
                ],
                'added' => [
                ],
                'removed' => [
                ],
                'modified' => [
                    'README.md',
                ],
            ],
            'repository' => [
                'id' => 4242,
                'name' => 'public-repo',
                'full_name' => 'baxterthehacker/public-repo',
            ],
        ]);
        $signature = \hash_hmac('sha1', $body, self::TEST_SECRET_TOKEN);

        $client->request(
            'POST',
            '/hooks/github',
            [],
            [],
            [
                'HTTP_X_GITHUB_EVENT' => 'push',
                'HTTP_X_HUB_SIGNATURE' => "sha1={$signature}",
            ],
            $body
        );

        static::assertSame(200, $client->getResponse()->getStatusCode());
        static::assertSame(GithubHookEvent::class.'.push', $client->getResponse()->getContent());

        $httplugClientMock = $client->getContainer()->get('httplug.client.mock');
        static::assertCount(1, $httplugClientMock->getRequests());
        static::assertSame('POST', $httplugClientMock->getRequests()[0]->getMethod());
        static::assertSame(
            'api.github.com',
            $httplugClientMock->getRequests()[0]->getUri()->getHost()
        );
        static::assertSame(
            '/repos/baxterthehacker/public-repo/statuses/0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c',
            $httplugClientMock->getRequests()[0]->getUri()->getPath()
        );
    }

    public function testGitlabMergeRequest(): void
    {
        $client = static::createClient();
        $objectManager = $client->getContainer()->get('doctrine')->getManager();
        $repository = (new Repository())
            ->setName('gitlabhq/gitlab-test')
            ->setEnabled(true)
            ->setAccessToken(self::TEST_ACCESS_TOKEN)
            ->setSecretToken(self::TEST_SECRET_TOKEN)
            ->setPlatform('gitlab')
            ->setPlatformId(4242);
        $objectManager->persist($repository);
        $objectManager->flush();

        $body = \json_encode([
            'object_kind' => 'merge_request',
            'user' => [
                'name' => 'Administrator',
                'username' => 'root',
                'avatar_url' => 'http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40&d=identicon',
            ],
            'project' => [
                'name' => 'Gitlab Test',
                'description' => 'Aut reprehenderit ut est.',
                'web_url' => 'http://example.com/gitlabhq/gitlab-test',
                'avatar_url' => null,
                'git_ssh_url' => 'git@example.com:gitlabhq/gitlab-test.git',
                'git_http_url' => 'http://example.com/gitlabhq/gitlab-test.git',
                'namespace' => 'GitlabHQ',
                'visibility_level' => 20,
                'path_with_namespace' => 'gitlabhq/gitlab-test',
                'default_branch' => 'master',
                'homepage' => 'http://example.com/gitlabhq/gitlab-test',
                'url' => 'http://example.com/gitlabhq/gitlab-test.git',
                'ssh_url' => 'git@example.com:gitlabhq/gitlab-test.git',
                'http_url' => 'http://example.com/gitlabhq/gitlab-test.git',
            ],
            'repository' => [
                'name' => 'Gitlab Test',
                'url' => 'http://example.com/gitlabhq/gitlab-test.git',
                'description' => 'Aut reprehenderit ut est.',
                'homepage' => 'http://example.com/gitlabhq/gitlab-test',
            ],
            'object_attributes' => [
                'id' => 99,
                'target_branch' => 'master',
                'source_branch' => 'ms-viewport',
                'source_project_id' => 14,
                'author_id' => 51,
                'assignee_id' => 6,
                'title' => 'MS-Viewport',
                'created_at' => '2013-12-03T17:23:34Z',
                'updated_at' => '2013-12-03T17:23:34Z',
                'st_commits' => null,
                'st_diffs' => null,
                'milestone_id' => null,
                'state' => 'opened',
                'merge_status' => 'unchecked',
                'target_project_id' => 4242,
                'iid' => 1,
                'description' => '',
                'source' => [
                    'name' => 'Awesome Project',
                    'description' => 'Aut reprehenderit ut est.',
                    'web_url' => 'http://example.com/awesome_space/awesome_project',
                    'avatar_url' => null,
                    'git_ssh_url' => 'git@example.com:awesome_space/awesome_project.git',
                    'git_http_url' => 'http://example.com/awesome_space/awesome_project.git',
                    'namespace' => 'Awesome Space',
                    'visibility_level' => 20,
                    'path_with_namespace' => 'awesome_space/awesome_project',
                    'default_branch' => 'master',
                    'homepage' => 'http://example.com/awesome_space/awesome_project',
                    'url' => 'http://example.com/awesome_space/awesome_project.git',
                    'ssh_url' => 'git@example.com:awesome_space/awesome_project.git',
                    'http_url' => 'http://example.com/awesome_space/awesome_project.git',
                ],
                'target' => [
                    'name' => 'Awesome Project',
                    'description' => 'Aut reprehenderit ut est.',
                    'web_url' => 'http://example.com/awesome_space/awesome_project',
                    'avatar_url' => null,
                    'git_ssh_url' => 'git@example.com:awesome_space/awesome_project.git',
                    'git_http_url' => 'http://example.com/awesome_space/awesome_project.git',
                    'namespace' => 'Awesome Space',
                    'visibility_level' => 20,
                    'path_with_namespace' => 'awesome_space/awesome_project',
                    'default_branch' => 'master',
                    'homepage' => 'http://example.com/awesome_space/awesome_project',
                    'url' => 'http://example.com/awesome_space/awesome_project.git',
                    'ssh_url' => 'git@example.com:awesome_space/awesome_project.git',
                    'http_url' => 'http://example.com/awesome_space/awesome_project.git',
                ],
                'last_commit' => [
                    'id' => 'da1560886d4f094c3e6c9ef40349f7d38b5d27d7',
                    'message' => 'fixed readme',
                    'timestamp' => '2012-01-03T23:36:29+02:00',
                    'url' => 'http://example.com/awesome_space/awesome_project/commits/da1560886d4f094c3e6c9ef40349f7d38b5d27d7',
                    'author' => [
                        'name' => 'GitLab dev user',
                        'email' => 'gitlabdev@dv6700.(none)',
                    ],
                ],
                'work_in_progress' => false,
                'url' => 'http://example.com/diaspora/merge_requests/1',
                'action' => 'open',
                'assignee' => [
                    'name' => 'User1',
                    'username' => 'user1',
                    'avatar_url' => 'http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40&d=identicon',
                ],
            ],
        ]);

        $client->request(
            'POST',
            '/hooks/gitlab',
            [],
            [],
            [
                'HTTP_X_GITLAB_EVENT' => 'Merge Request Hook',
                'HTTP_X_GITLAB_TOKEN' => self::TEST_SECRET_TOKEN,
            ],
            $body
        );

        static::assertSame(200, $client->getResponse()->getStatusCode());
        static::assertSame(GitlabHookEvent::class.'.merge_request.open', $client->getResponse()->getContent());

        $httplugClientMock = $client->getContainer()->get('httplug.client.mock');
        static::assertCount(0, $httplugClientMock->getRequests());
    }
}
```

Basically, those controllers are just parsing data and saving simple entities.

Any idea of why?

Maybe it's not related directly to this bundle, but it's falling only at rollback.

**Comment by dmaicher** [comment] 2017-10-24 13:26
Hmm this seems weird. Are you manually closing the connection somewhere?

Can you check within `StaticDriver::rollBack()` the status of the connection when this happens?

**Comment by Soullivaneuh** [comment] 2017-10-24 13:45
> Hmm this seems weird. Are you manually closing the connection somewhere?

No, AFAIK. Which code part should I search for?

> Can you check within `StaticDriver::rollBack()` the status of the connection when this happens?

Could you pleas elaborate? Which test code would you like me to insert?

**Comment by Soullivaneuh** [comment] 2017-10-24 13:50
It's very weird, I run the same phpunit command twice, one worked, the another didn't:

```
sullivan@58d5a9588f74:/code$ make coverage
php -dzend_extension=xdebug.so `which phpunit` --coverage-text --colors=never --coverage-html coverage

 // Clearing the cache for the test environment with debug true                                                         

 [OK] Cache for the "test" environment (debug=true) was successfully cleared.                                           

PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

....................
Remaining vendor deprecation notices (76)
PDO::rollBack(): MySQL server has gone away

Remaining vendor deprecation notices (76)
Makefile:22: recipe for target 'coverage' failed
make: *** [coverage] Error 2
sullivan@58d5a9588f74:/code$ make coverage
php -dzend_extension=xdebug.so `which phpunit` --coverage-text --colors=never --coverage-html coverage

 // Clearing the cache for the test environment with debug true                                                         

 [OK] Cache for the "test" environment (debug=true) was successfully cleared.                                           

PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

..............................................                    46 / 46 (100%)

Time: 2.03 minutes, Memory: 125.41MB

OK (46 tests, 534 assertions)

Generating code coverage report in HTML format ... done
```

Maybe related to a MySQL timeout?

**Comment by dmaicher** [comment] 2017-10-24 13:51
Yes indeed can be a timeout: https://dev.mysql.com/doc/refman/5.7/en/gone-away.html

**Comment by dmaicher** [comment] 2017-10-24 13:52
Maybe with `dump($con)` we can see something but not sure :/ A bit tricky to debug

**Comment by Soullivaneuh** [comment] 2017-10-24 14:03
I tried:

```
public static function rollBack()
{
    foreach (self::$connections as $con) {
        try {
            $con->rollBack();
        } catch (\PDOException $exception) {
            dump($con);die;
        }
    }
}
```

But nothing shown when the error occurs.

I'll try to increase the timeout.

**Comment by Soullivaneuh** [comment] 2017-10-24 14:18
```
mysql> SHOW VARIABLES LIKE '%timeout%';
+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 10       |
| delayed_insert_timeout      | 300      |
| have_statement_timeout      | YES      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 50       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 28800    |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 30       |
| net_write_timeout           | 60       |
| rpl_stop_slave_timeout      | 31536000 |
| slave_net_timeout           | 60       |
| wait_timeout                | 28800    |
+-----------------------------+----------+
13 rows in set (0.00 sec)
```

This is indeed may be a little short for test env.

**Comment by dmaicher** [comment] 2017-10-24 14:20
here my values for my local docker mysql instance:

```
mysql> SHOW VARIABLES LIKE '%timeout%';
+----------------------------+----------+
| Variable_name              | Value    |
+----------------------------+----------+
| connect_timeout            | 10       |
| delayed_insert_timeout     | 300      |
| innodb_lock_wait_timeout   | 50       |
| innodb_rollback_on_timeout | OFF      |
| interactive_timeout        | 28800    |
| lock_wait_timeout          | 31536000 |
| net_read_timeout           | 30       |
| net_write_timeout          | 60       |
| slave_net_timeout          | 3600     |
| wait_timeout               | 28800    |
+----------------------------+----------+
10 rows in set (0.00 sec)
```

**Comment by Soullivaneuh** [comment] 2017-10-24 14:25
Well, you have the same values. :-|

I'm trying with this:

```
[mysqld]
connect_timeout=20
net_read_timeout=60
net_write_timeout=120
```

Will tell if it works after many test launches...

**Comment by dmaicher** [comment] 2017-10-24 14:25
Does this show anything?

```php
public static function rollBack()
{
    foreach (self::$connections as $con) {
        if ($con->rollBack() === false) {
           dump($con);die;
        }
    }
}

**Comment by Soullivaneuh** [comment] 2017-10-24 15:22
I tried:

```php
public static function rollBack()
{
    foreach (self::$connections as $con) {
        if (false === $con->rollBack()) {
            dump($con);die;
        }
    }
}
```

But I have nothing more except the error.

This is quite frustrating to not know which timeout parameter I have to change... if I have to change one of them.

I still have some Mysql crash with my new config, but "seems" to happen less regularly.

**Comment by dmaicher** [comment] 2017-10-24 16:28
Does it always crash at the same test? Is it a test that takes really long?

**Comment by Soullivaneuh** [comment] 2017-10-24 17:30
Well, I'm now on a more powerful computer and I can't reproduce the issue. :trollface: 

So I'm pretty sure it's related to timeout, but which one?

I'll try by setting a ridiculous low value per timeout option to try to reproduce the issue.

**Comment by Soullivaneuh** [comment] 2017-10-24 17:39
Well... I tried with this:

```
[mysqld]
connect_timeout=1
net_read_timeout=1
net_write_timeout=1
```

And... it's still working. :-S

I definitely have to try again on the other computer, this is more weird than I was thinking.

**Comment by Jean85** [comment] 2017-10-25 08:18
We use this (in production too) to solve the "gone away" issue: https://github.com/facile-it/doctrine-mysql-come-back

**Comment by Soullivaneuh** [comment] 2017-10-25 08:31
@Jean85 well, looking at the code part: https://github.com/facile-it/doctrine-mysql-come-back/blob/3875115784de4556b3c622cdcec74ac74df3a0a3/src/Driver/ServerGoneAwayExceptionsAwareTrait.php#L26-L55

It's looks more like a "Shhht, this never happened!" workaround than a fix. Am I right? :smile: 

It would be better to find where the issue.

**Comment by dmaicher** [comment] 2017-10-25 08:42
I think this must be some configuration issue or a bug. I mean I never ever had this issue. Not in production and not locally.

Which mysql version and php version are you using?

```
$ php -i | grep mysql
Additional .ini files parsed => /etc/php/7.1/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.1/cli/conf.d/20-mysqli.ini,
/etc/php/7.1/cli/conf.d/20-pdo_mysql.ini,
mysqli
Client API library version => mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
mysqli.allow_local_infile => On => On
mysqli.allow_persistent => On => On
mysqli.default_host => no value => no value
mysqli.default_port => 3306 => 3306
mysqli.default_pw => no value => no value
mysqli.default_socket => no value => no value
mysqli.default_user => no value => no value
mysqli.max_links => Unlimited => Unlimited
mysqli.max_persistent => Unlimited => Unlimited
mysqli.reconnect => Off => Off
mysqli.rollback_on_cached_plink => Off => Off
mysqlnd
mysqlnd => enabled
Version => mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
API Extensions => mysqli,pdo_mysql
mysqlnd statistics =>  
PDO drivers => mysql
pdo_mysql
Client API version => mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock

**Comment by Jean85** [comment] 2017-10-25 08:47
> It's looks more like a "Shhht, this never happened!" workaround than a fix. Am I right? :smile:

Well, in our case we have a few routes that take a long time, so we cannot relax the timeout just for those; so that's a feasible solution for us.

In this case, since it's in a test env, it shouldn't take this long so yeah, maybe you should find the root cause first.

**Comment by Soullivaneuh** [comment] 2017-10-25 10:29
> I think this must be some configuration issue or a bug.

I agree. And seems to be related according to the computer power.

My `php -i` result:

```
sullivan@2184e611a382:/code$ php -i | grep mysql
Configure Command =>  './configure'  '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--disable-cgi' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pcre-regex=/usr' 'build_alias=x86_64-linux-musl'
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
mysqlnd
mysqlnd => enabled
Version => mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
API Extensions => pdo_mysql
mysqlnd statistics =>  
PDO drivers => sqlite, mysql
pdo_mysql
Client API version => mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
pdo_mysql.default_socket => no value => no value
PHP_EXTENSIONS => zip     pdo     pdo_mysql     intl     gd     pcntl     bcmath     shmop     mbstring     exif     mcrypt     imap     soap
TOOLS_PACKAGES => bash     make     wget     curl     git     openssh-client     mysql-client
$_SERVER['PHP_EXTENSIONS'] => zip     pdo     pdo_mysql     intl     gd     pcntl     bcmath     shmop     mbstring     exif     mcrypt     imap     soap
$_SERVER['TOOLS_PACKAGES'] => bash     make     wget     curl     git     openssh-client     mysql-client
$_ENV['PHP_EXTENSIONS'] => zip     pdo     pdo_mysql     intl     gd     pcntl     bcmath     shmop     mbstring     exif     mcrypt     imap     soap
$_ENV['TOOLS_PACKAGES'] => bash     make     wget     curl     git     openssh-client     mysql-client
```

And I use MySQL 5.7 latest Docker image.

**Comment by Soullivaneuh** [comment] 2017-10-25 10:34
I tried with:

```
[mysqld]
connect_timeout=1
net_read_timeout=1
net_write_timeout=1
```

MySQL result:

```
mysql> SHOW VARIABLES LIKE '%timeout%';
+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 2        |
| delayed_insert_timeout      | 300      |
| have_statement_timeout      | YES      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 50       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 28800    |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 1        |
| net_write_timeout           | 1        |
| rpl_stop_slave_timeout      | 31536000 |
| slave_net_timeout           | 60       |
| wait_timeout                | 28800    |
+-----------------------------+----------+
```

And the test suite... passed! I'm going to be crazy! :sweat_smile: 

So... not related to timeout?

**Comment by dmaicher** [comment] 2017-10-25 15:27
yeah sorry no idea :cry: Closing this issue as its not related to this bundle

**Closed by dmaicher** 2017-10-25 15:27 UTC

**Comment by Soullivaneuh** [comment] 2017-10-25 22:28
I understand the close statement.

If I get a solution, I'll paste it here.
