### ISSUE TITLE
Error "There is already an active transaction" when i attempt persist inside setUpBeforeClass()

### ISSUE THREAD

**Issue by andaniel05** [dmaicher/doctrine-test-bundle#108] opened 2020-01-17 15:29 UTC
My test case:

```php
<?php
declare(strict_types=1);

namespace App\Tests;

use App\Entity\Country;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class MyTest extends WebTestCase
{
    public static function setUpBeforeClass()
    {
        $country = new Country;
        $country->setCode('CU');

        static::bootKernel();
        $em = static::$container->get('doctrine')->getManager();
        $em->persist($country);
        $em->flush();
    }

    public function test()
    {
        $this->assertTrue(true);
    }
}
```

Produces the next error:

![1](https://user-images.githubusercontent.com/21297818/72624045-31737200-3914-11ea-972b-ab2536882a01.png)

My environment:
Symfony: 4.4.2
dama/doctrine-test-bundle: 6.3.1

**Comment by dmaicher** [comment] 2020-01-20 16:30
I checked this and doing db changes from within `setUpBeforeClass` seems tricky to supoort with this bundle.

Actually `setUpBeforeClass` is executed before PHPUnit's `BeforeTestHook` which starts the transaction on the DB connection before your `test()` method runs.

So I only see 2 options:

- move the db logic from `setUpBeforeClass` into `setUp` which fits more into the philosophy of this bundle as it wraps all single test cases (including any setUp) into a db transaction.

- try adding `StaticDriver::commit();` at the very end of your `setUpBeforeClass` method

**Comment by sabat24** [comment] 2020-04-27 21:37
In my case I have to use `setUpBeforeClass` because I load there some initial fixtures for all tests. Such code can't be moved to the `setUp` because in such way there will be no point to use that bundle. I tried to add `StaticDriver::commit();` at the end of `setUpBeforeClass` which is acceptable solution for me - but I still get an error about active transaction.

```
public static function setUpBeforeClass(): void
    {
        self::bootKernel();
        $projectDir = self::$kernel->getProjectDir();
        $fixtures = [
            $projectDir . '\fixtures\news.yaml',
        ];
        // returns the real and unchanged service container
        $container = self::$kernel->getContainer();
        $loader = $container->get('fidry_alice_data_fixtures.loader.doctrine');

        $loader->load($fixtures);
    }
```

Error is caused by `load` method from last line. Is there some way to handle such cases? I can remove my fixtures in `tearDownAfterClass` and I only need that bundle to deal with tests inside that class.

**Comment by dmaicher** [comment] 2020-04-29 12:07
I just tried that and for me it works :confused: 

See https://github.com/dmaicher/doctrine-test-bundle/compare/setup_before_class?expand=1#diff-03fced164fdf7a5fedfdcc4e5733a19fR65

1. insert a row in `setUpBeforeClass`
2. row exists in test cases
3. any added rows in test cases are rolled back

@sabat24 can you debug somehow why the connection you have is not committed with `StaticDriver::commit()` at the end of  `setUpBeforeClass`?

**Comment by sabat24** [comment] 2020-04-29 12:26
I use [hautelook/AliceBundle](https://github.com/hautelook/AliceBundle) to load fixtures to DB in `setUpBeforeClass`. I think that mentioned bundle starts a transaction inside `$loader->load($fixtures);` method. Then your bundle probably because of some kind of listener applied starts another transaction which causes my problem.
If I could somehow tell your bundle to disable that listener on `setUpBeforeClass` and enable it only on `setUp` methods it would solve my problem.

**Comment by dmaicher** [comment] 2020-04-29 12:31
@sabat24 can you try this?

```php
    public static function setUpBeforeClass(): void
    {
        StaticDriver::setKeepStaticConnections(false);
        // your logic
        StaticDriver::setKeepStaticConnections(true);
    }
```

**Comment by sabat24** [comment] 2020-04-29 18:44
It worked and it was exactly was I looked for. Thank you.

**Closed** 2020-04-29 20:14 UTC
